name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version: ["20.5", "21.0"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Unit Tests

      - name: Install unit test dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      # Integration tests

      # Verify a target git package does not exist
      - name: Test missing dummy_rez_package
        id: no-package-from-git
        continue-on-error: true
        shell: bash
        run: rez env dummy_rez_package -- echo "resolve successful"

      - name: Build a package from git
        id: build-from-git
        uses: ./
        with:
          from_git: https://github.com/captainhammy/dummy-rez-package.git

      # Verify a target git package exists
      - name: Test dummy_rez_package was built from git
        id: successful-package-from-git
        shell: bash
        run: |
          rez env dummy_rez_package -- echo "resolve successful"

      - name: Test missing dummy_rez_package-0.0.2
        id: no-package-from-git-with-tag
        continue-on-error: true
        shell: bash
        run: rez env dummy_rez_package-0.0.2 -- echo "resolve successful"

      - name: Build a package from git from a specific tag
        id: build-from-git-with-tag
        uses: ./
        with:
          from_git: https://github.com/captainhammy/dummy-rez-package.git
          git_tag: 0.0.2

      # Verify a target git package version exists
      - name: Test dummy_rez_package at a specific tag was built from git
        id: successful-package-from-git-tag
        shell: bash
        run: |
          rez env dummy_rez_package-0.0.2 -- echo "resolve successful"

      # Test building a simple package with no variants.
      - name: Build test package with no variants
        id: build-test-package
        uses: ./
        with:
          package_root: ./tests/test_install_package
          extra: -- --debug-output

      # Verify the package was built by resolving it and running a command.
      - name: Test package build success
        shell: bash
        run: rez env test_install_package -- echo "resolve successful"

      - name: Validate build action output information
        shell: bash
        run: |
          test ${{ steps.build-test-package.outputs.package_name }} = test_install_package
          test ${{ steps.build-test-package.outputs.package_version }} = 0.0.2
          test ${{ steps.build-test-package.outputs.package_variant }} = ""

      # Install some packages that we can use to test building variants based on them.
      - name: Install variant packages
        uses: captainhammy/install-rez-packages-action@v1
        with:
          packages: "six==1.14.0,six==1.15.0"

      # Explicitly build the 0 variant.
      - name: Build test package with variant 0
        id: build-variant-0
        uses: ./
        with:
          variant: 0
          package_root: ./tests/test_install_package_with_variants

      # Verify the correct variant was built by resolving it via its dependency version.
      - name: Test resolve (variant 0)
        shell: bash
        run: rez env test_install_package_with_variants six-1.14.0 -- echo "resolve successful"

      - name: Validate variant build action output information
        shell: bash
        run: |
          test ${{ steps.build-variant-0.outputs.package_name }} = test_install_package_with_variants
          test ${{ steps.build-variant-0.outputs.package_version }} = 0.0.1
          test ${{ steps.build-variant-0.outputs.package_variant }} = 0

      # Build the package without specifying a variant. This will build all the variants.
      - name: Build test package (all variants)
        uses: ./
        with:
          package_root: ./tests/test_install_package_with_variants

      # Verify that variant 1 was built by resolving it via its dependency version.
      - name: Test resolve (variant 1)
        shell: bash
        run: rez env test_install_package_with_variants six-1.15.0 -- echo "resolve successful"

      # Remove the built packages so we can test build again
      - name: Remove built test packages
        shell: bash
        run: |
          rez rm --package test_install_package_with_variants-0.0.1 `rez config local_packages_path`

      # Test building variant 1 by using a request
      - name: Build test package variant by request
        id: build-by-request
        uses: ./
        with:
          package_root: ./tests/test_install_package_with_variants
          variant_from_request: six-1.15

      # Verify that variant 1 was built
      - name: Test resolve by request (variant 1)
        shell: bash
        run: rez env test_install_package_with_variants six-1.15.0 -- echo "resolve successful"

      - name: Validate variant build action output information
        shell: bash
        run: |
          test ${{ steps.build-by-request.outputs.package_name }} = test_install_package_with_variants
          test ${{ steps.build-by-request.outputs.package_version }} = 0.0.1
          test ${{ steps.build-by-request.outputs.package_variant }} = 1

      # Verify the variant 0 was not built.
      - name: Test resolve (variant 0)
        id: variant-0-not-built
        continue-on-error: true
        shell: bash
        run: rez env test_install_package_with_variants six-1.14.0 -- echo "resolve successful"

      - name: Validate previous step failure
        if: steps.variant-0-not-built.outcome != 'failure'
        run: exit 1

      # Test with a request that does not match any variants.
      - name: Build test package variant by request with no matching variants
        id: no-matching-variants
        continue-on-error: true
        uses: ./
        with:
          package_root: ./tests/test_install_package_with_variants
          variant_from_request: foo-123

      - name: Validate previous step failure
        if: steps.no-matching-variants.outcome != 'failure'
        run: exit 1

      # Test with a request that matches too many variants.
      - name: Build test package variant by request with too many matching variants
        id: too-many-matching-variants
        continue-on-error: true
        uses: ./
        with:
          package_root: ./tests/test_install_package_with_variants
          variant_from_request: six

      - name: Validate previous step failure
        if: steps.too-many-matching-variants.outcome != 'failure'
        run: exit 1

